DROP USER IF EXISTS HelpDesk;
DROP USER IF EXISTS DefaultUser;

CREATE USER HelpDesk WITHOUT LOGIN;
GO

CREATE USER DefaultUser WITHOUT LOGIN;
GO


ALTER ROLE db_datareader ADD MEMBER HelpDesk;

ALTER ROLE db_datareader ADD MEMBER DefaultUser;


GRANT UNMASK TO DefaultUser;

GRANT SELECT, UPDATE ON AspNetUsers(UserName) TO HelpDesk;

GRANT SELECT, UPDATE TO DefaultUser;


